database:
  driver: postgresql
  host: localhost
  port: 5432
  name: kk_db
  user: postgres
  password: 123
  pool_size: 10
  max_overflow: 20
  pool_recycle: 1800
server:
  host: 0.0.0.0
  port: 8001
  save_path: D:\kk\code\kk\manager_server\uploads