database:
  driver: postgresql
  host: localhost
  port: 5432
  name: kk_db
  user: postgres
  password: 123
  pool_size: 10
  max_overflow: 20
  pool_recycle: 1800
server:
  host: 0.0.0.0
  port: 8001
  device_listen_port: 9527
  device_refresh_time: 180
  image_hash_distance: 18
  gps_distance: 50
  jwt_secret: 31ed2213r4dwqq12
  save_path: D:\kk\code\kk\manager_server\uploads
  routes_file: D:\kk\code\kk\manager_server\routes.json